### ISSUE TITLE
这个系统完成了吗

### ISSUE THREAD

**Issue by juforg** [JiangTJ/enterpriseAssetManagement#2]
看着不错 想用于 正式环境

**Comment by jiangtj** [comment]
还没有完成

**Comment by juforg** [comment]
能列出你的开发计划吗，想看下你的功能点
我想可以 开个微信子项目，用于配合这个项目
功能点：1. 通过微信连接蓝牙条码二维码打印机（貌似公众号支持，企业微信没说支持，虽然我是想在企业微信中做）
2. 录入资产：选择资产类型和部门 ，拍照上传后，调用1 的功能 打印条码 贴在 资产上就好
3. 盘点，主项目定时生成盘点任务后，自动指派给每个部门的盘点员，盘点员在微信中开始盘点任务，直接一个个扫描资产上贴的条码就好，没扫描到的就是缺失资产，需要盘点员一个个说明，主项目根据盘点员的说明重新修改部门的资产状态
4. 资产领用：企业微信中的员工，扫描条码 ，点击领用，部门资产管理员确认后，主项目中资产状态就自动修改了
5. 资产维修：资产管理员扫描资产后点击报修，自动微信通知主项目中 该资产类型的管理员维修，资产状态也立即修改，资产管理员维修完后，同样扫描下，输入维修内容，点击完成 就好了

**Comment by jiangtj** [comment]
这里有两个消息  
好消息是：您所说的大部分功能都有考虑  
坏消息是：这个是我的毕设项目，之前5月份答辩，将需演示的功能点写出来了，但未考虑各个功能的细节，甚至框架都没完善。目前正在逐步完善系统，这可能需要很长的时间。  
_附：关于资产领用，员工扫描条码，意味着员工就在物品的旁边。所以将流程 员工领用 -> 管理员确认
 调整为 员工申请 -> 员工领用 -> 消息通知，是不是更合理_
_附：关于项目进度，可以在Projects中查看_
