### ISSUE TITLE
能否加入一些功能呢？

### ISSUE THREAD

**Issue by bruclan** [JiangTJ/enterpriseAssetManagement#4]
1、只有超级管理员可以浏览所有资产（任意状态）。
2、普通用户只能浏览“正常”状态下的资产和自己借入的资产。
3、登陆后同时显示员工ID。
4、“借还登记”中的“借/还人id”能否进行下类型验证。传递非整形数值虽然报错但依然可以写入数据库，只是没有写入“assets_borrow”表中。

现在需要这几个功能，谢谢啦。

**Comment by jiangtj** [comment]
第一二条，权限相关的目前不想做调整，不过后续会开发首页，用于展示登录人借入的资产  
第三点，已记下  
第四点，已知问题，assets_borrow表相关功能未开发（之前开发过程中遗漏的模块），在后续开发过程中修复

**Comment by jiangtj** [comment]
在最新的master上，已经完成一下几项

- 首页，当前登录用户的借用物品的展示
- 登录用户详情展示（侧边菜单->用户退出按钮处）
- 借还登记，借/还人id原本的输入框调整为选择框
